name: Deploy to Docker Hub

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout
      
      - name: Login to Docker Hub
        uses: docker/login-action
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      
      - name: Build and push image
        uses: docker/build-push-action
        with:
          context: .
          file: ./src/Fakester.NET.API/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_REPOSITORY }}:latest
